apiVersion: v1
kind: Secret
metadata:
  name: openshifttestapp-application-secret
data:
  ConnectionStrings__default: #{Deployment.CONNECTIONSTRING}#
---
apiVersion: v1
kind: Secret
metadata:
  name: openshifttestapp-database-secret
data:
  SA_PASSWORD: #{Deployment.DATABASEPASSWORD}#
---
apiVersion: v1
kind: Secret
metadata:
  name: openshifttestapp-azure-private-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #{Deployment.DOCKERCONFIGJSON}#